name: Generate snake animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours

permissions:
  contents: write   # 👈 add here, at the same level as "on:" and "jobs:"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake (Platane snk v3)
        uses: Platane/snk@v3
        with:
          github_user_name: Riyaz-mazumder
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
